### ISSUE TITLE
Add actual camera images to Demo Mode

### ISSUE THREAD

**Issue by Conr86** [SFXRescue/SIGHTSInterface#23]
It would be nice to have photos from inside the maze or something like that to really show what the robot is like to drive.

**Comment by WilliamsJack** [comment]
273c12a096490d072762ba02e46f63dc6f98c9fa adds code to display camera images from a random set. Sets are defined in folders with a name matching the regex `set-\d+`.

`set-0` is an easter egg.

**Comment by WilliamsJack** [comment]
I'm happy to close this - what are your thoughts @Conr86? There are now 8 sets of images, and the possibility to add as many more as we want (of course with the penalty of increasing the size of the repository).

**Comment by Conr86** [comment]
Yep, I'm happy to close it, the new images are excellent! 

The only issue I've found is, with the first two sets you added, the images are slightly smaller (or have a different aspect ratio) leading to a minor visual glitch where the bottom camera images are pressed up against the service controls and speed indicators:

![image](https://user-images.githubusercontent.com/5257675/68536968-074f8200-03b0-11ea-8cd5-879c9463ee5b.png)
