### ISSUE TITLE
Update demo mode features

### ISSUE THREAD

**Issue by WilliamsJack** [SFXRescue/SIGHTSInterface#24]
At the time of writing, there have been 87 commits to master since the last non-trivial revision to demo mode, with more flowing in every day. Demo mode is falling behind, meaning potential users and contributors may come to the incorrect conclusion that SIGHTS software is unstable or buggy.

It may be a good idea to include a dismissable alert in demo mode explaining that bugs may exist in demo mode that do not exist in the full version of SIGHTS.

Key areas:
- [x] Visual config editor
- [x] Bootoast notifications - some wording may be different between demo and normal modes
- [x] Don't attempt requests to /RPC2 while in demo mode
- [x] Display mock data for service and message logs
- [x] Set service state to "running"

Small optional additions/extras:
- [x] Increment uptime counter
- [x] Generate random data (every second?) for CPU temp, CO2 level and TVOC level
- [x] Slowly decrease charge level
- [x] Populate config selector with dummy configs (doesn't need to be selectable)
- [x] Disconnect dummy websockets if the user shuts down or restarts the robot
- [x] Update keyboard speed indicator when keys are pressed

Part of this process will include stripping out https://picsum.photos and completing issue #23.

This issue should be completed before the announcement of SIGHTS v1.0 release, and the demo at https://www.sfxrescue.com/interfacedemo/ updated.

**Comment by Conr86** [comment]
I strongly agree with this issue. Definitely something we need done before v1.0.

We might want to make it so most of the actual scripts don't run during demo mode.

**Comment by WilliamsJack** [comment]
Awesome work on 681c62c7491bec18a7d0a42c59553ea0a28f5d90 @Conr86, the activity on the main screen looks great! I love watching everything coming to life when demo mode is enabled.

**Comment by Conr86** [comment]
What's left to do for the Visual Editor? It works as far as I can tell. Was there something else you had in mind?

**Comment by WilliamsJack** [comment]
It was mostly just a "key area" to look at, as long as it works well, that's great.
Does it update the advanced editor?

**Comment by WilliamsJack** [comment]
Ok, it does update the advanced editor, however there are a few issues with the alerts that I'll fix now.

**Comment by WilliamsJack** [comment]
Just did "Disconnect dummy websockets if the user shuts down or restarts the robot" the easy way by refreshing the page - but this means when you disable demo mode, you can start using the robot normally again.

**Comment by WilliamsJack** [comment]
👍
